// <auto-generated />
using System;
using LearnLangs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnLangs.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124104731_SeedPlacementTestsDemo")]
    partial class SeedPlacementTestsDemo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnLangs.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<string>("DefaultPronunciationLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTranslateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultTranslateTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Has30DayStreakReward")
                        .HasColumnType("bit");

                    b.Property<bool>("Has7DayStreakReward")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredUiTheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowPronunciationRawJson")
                        .HasColumnType("bit");

                    b.Property<int>("TotalXP")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LearnLangs.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basics of Spanish",
                            Name = "Spanish – Beginner"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Beginner Mandarin: greetings, numbers, self-intro with pinyin.",
                            Name = "Chinese course"
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SetId", "OrderIndex");

                    b.ToTable("DictationItems");

                    b.HasData(
                        new
                        {
                            Id = 2101,
                            AudioUrl = "/audio/demo1.mp3",
                            OrderIndex = 1,
                            SetId = 2100,
                            Transcript = "I've been meaning to ask you for some advice about restaurants."
                        },
                        new
                        {
                            Id = 2102,
                            AudioUrl = "/audio/demo2.mp3",
                            OrderIndex = 2,
                            SetId = 2100,
                            Transcript = "I need to book somewhere to celebrate my sister's thirtieth birthday."
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "OrderIndex");

                    b.ToTable("DictationSets");

                    b.HasData(
                        new
                        {
                            Id = 2100,
                            Level = "B2",
                            OrderIndex = 1,
                            Title = "Cam 20 – Test 1 – Part 1 (Demo)",
                            TopicId = 2000
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DictationTopics");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            CoverUrl = "/img/ielts.png",
                            Description = "Mini demo",
                            Title = "IELTS Listening (Demo)"
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.UserDictationProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("LastIndex")
                        .HasColumnType("int");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SetId")
                        .IsUnique();

                    b.ToTable("UserDictationProgresses");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackMeaningVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("ExampleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlashcardSetId")
                        .HasColumnType("int");

                    b.Property<string>("FrontWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Phonetic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardSetId");

                    b.HasIndex("DeckId", "OrderIndex");

                    b.ToTable("FlashcardCards");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FlashcardCategories");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Mode", "OrderIndex");

                    b.ToTable("FlashcardDecks");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAdminOwned")
                        .HasColumnType("bit");

                    b.Property<string>("Lang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Part")
                        .HasColumnType("int");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FlashcardSet");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GameLevelId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.ExamAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId", "ExamId");

                    b.ToTable("ExamAttempts");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.GameLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameLevels");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.GameQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerMapJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectText")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("GameLevelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ImagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SentenceAnswer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SentenceShuffled")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameLevelId");

                    b.ToTable("GameQuestions");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("GameLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GameLevelId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("LearnLangs.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            OrderIndex = 1,
                            Title = "Greetings",
                            XpReward = 10
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            OrderIndex = 2,
                            Title = "Numbers",
                            XpReward = 10
                        },
                        new
                        {
                            Id = 101,
                            CourseId = 100,
                            OrderIndex = 1,
                            Title = "Lesson 1 – Greetings",
                            XpReward = 30
                        },
                        new
                        {
                            Id = 102,
                            CourseId = 100,
                            OrderIndex = 2,
                            Title = "Lesson 2 – Numbers 1–10",
                            XpReward = 30
                        },
                        new
                        {
                            Id = 103,
                            CourseId = 100,
                            OrderIndex = 3,
                            Title = "Lesson 3 – Self-Introduction",
                            XpReward = 40
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.PlacementTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.ToTable("PlacementTests");

                    b.HasData(
                        new
                        {
                            TestId = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiểm tra nhanh ngữ pháp và từ vựng giao tiếp hàng ngày.",
                            DurationMinutes = 10,
                            IsActive = true,
                            TestName = "General English",
                            TestType = 1,
                            TotalQuestions = 5
                        },
                        new
                        {
                            TestId = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bài test phù hợp học sinh, tập trung cấu trúc câu cơ bản.",
                            DurationMinutes = 10,
                            IsActive = true,
                            TestName = "For Schools",
                            TestType = 2,
                            TotalQuestions = 5
                        },
                        new
                        {
                            TestId = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiểm tra vốn từ vựng và cấu trúc dùng trong môi trường công sở.",
                            DurationMinutes = 10,
                            IsActive = true,
                            TestName = "Business English",
                            TestType = 3,
                            TotalQuestions = 5
                        },
                        new
                        {
                            TestId = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bài test thân thiện cho người mới bắt đầu và trẻ em.",
                            DurationMinutes = 10,
                            IsActive = true,
                            TestName = "Young Learners",
                            TestType = 4,
                            TotalQuestions = 5
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FillInTheBlankAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMultipleChoice")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ShortAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "A",
                            IsMultipleChoice = true,
                            LessonId = 1,
                            OptionA = "Hello",
                            OptionB = "Goodbye",
                            OptionC = "Please",
                            OptionD = "Thanks",
                            Prompt = "Hola = ?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "B",
                            IsMultipleChoice = true,
                            LessonId = 2,
                            OptionA = "One",
                            OptionB = "Two",
                            OptionC = "Three",
                            OptionD = "Four",
                            Prompt = "Dos = ?"
                        },
                        new
                        {
                            Id = 1001,
                            CorrectAnswer = "B",
                            IsMultipleChoice = true,
                            LessonId = 101,
                            OptionA = "Tạm biệt",
                            OptionB = "Xin chào",
                            OptionC = "Cảm ơn",
                            OptionD = "Xin lỗi",
                            Prompt = "“你好” nghĩa là gì?"
                        },
                        new
                        {
                            Id = 1002,
                            CorrectAnswer = "A",
                            IsMultipleChoice = true,
                            LessonId = 101,
                            OptionA = "Chào buổi sáng",
                            OptionB = "Chúc ngủ ngon",
                            OptionC = "Chúc mừng",
                            OptionD = "Hẹn gặp lại",
                            Prompt = "“早上好” nghĩa là…"
                        },
                        new
                        {
                            Id = 1003,
                            CorrectAnswer = "B",
                            IsMultipleChoice = true,
                            LessonId = 101,
                            OptionA = "Bạn tên gì?",
                            OptionB = "Bạn khỏe không?",
                            OptionC = "Bạn ở đâu?",
                            OptionD = "Bạn bao nhiêu tuổi?",
                            Prompt = "“你好吗？” nghĩa là…"
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.QuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            OptionId = 1001,
                            IsCorrect = false,
                            OptionText = "go",
                            OrderNumber = 1,
                            QuestionId = 101
                        },
                        new
                        {
                            OptionId = 1002,
                            IsCorrect = true,
                            OptionText = "goes",
                            OrderNumber = 2,
                            QuestionId = 101
                        },
                        new
                        {
                            OptionId = 1003,
                            IsCorrect = false,
                            OptionText = "going",
                            OrderNumber = 3,
                            QuestionId = 101
                        },
                        new
                        {
                            OptionId = 1004,
                            IsCorrect = false,
                            OptionText = "went",
                            OrderNumber = 4,
                            QuestionId = 101
                        },
                        new
                        {
                            OptionId = 1005,
                            IsCorrect = false,
                            OptionText = "He go to school.",
                            OrderNumber = 1,
                            QuestionId = 102
                        },
                        new
                        {
                            OptionId = 1006,
                            IsCorrect = true,
                            OptionText = "He goes to school.",
                            OrderNumber = 2,
                            QuestionId = 102
                        },
                        new
                        {
                            OptionId = 1007,
                            IsCorrect = false,
                            OptionText = "He to school goes.",
                            OrderNumber = 3,
                            QuestionId = 102
                        },
                        new
                        {
                            OptionId = 1008,
                            IsCorrect = false,
                            OptionText = "Goes he to school.",
                            OrderNumber = 4,
                            QuestionId = 102
                        },
                        new
                        {
                            OptionId = 1009,
                            IsCorrect = false,
                            OptionText = "goed",
                            OrderNumber = 1,
                            QuestionId = 103
                        },
                        new
                        {
                            OptionId = 1010,
                            IsCorrect = true,
                            OptionText = "went",
                            OrderNumber = 2,
                            QuestionId = 103
                        },
                        new
                        {
                            OptionId = 1011,
                            IsCorrect = false,
                            OptionText = "goes",
                            OrderNumber = 3,
                            QuestionId = 103
                        },
                        new
                        {
                            OptionId = 1012,
                            IsCorrect = false,
                            OptionText = "going",
                            OrderNumber = 4,
                            QuestionId = 103
                        },
                        new
                        {
                            OptionId = 1013,
                            IsCorrect = false,
                            OptionText = "a",
                            OrderNumber = 1,
                            QuestionId = 104
                        },
                        new
                        {
                            OptionId = 1014,
                            IsCorrect = true,
                            OptionText = "an",
                            OrderNumber = 2,
                            QuestionId = 104
                        },
                        new
                        {
                            OptionId = 1015,
                            IsCorrect = false,
                            OptionText = "the",
                            OrderNumber = 3,
                            QuestionId = 104
                        },
                        new
                        {
                            OptionId = 1016,
                            IsCorrect = false,
                            OptionText = "no article",
                            OrderNumber = 4,
                            QuestionId = 104
                        },
                        new
                        {
                            OptionId = 1017,
                            IsCorrect = true,
                            OptionText = "I'm fine, thank you.",
                            OrderNumber = 1,
                            QuestionId = 105
                        },
                        new
                        {
                            OptionId = 1018,
                            IsCorrect = false,
                            OptionText = "I'm twenty years.",
                            OrderNumber = 2,
                            QuestionId = 105
                        },
                        new
                        {
                            OptionId = 1019,
                            IsCorrect = false,
                            OptionText = "I am from student.",
                            OrderNumber = 3,
                            QuestionId = 105
                        },
                        new
                        {
                            OptionId = 1020,
                            IsCorrect = false,
                            OptionText = "I play football.",
                            OrderNumber = 4,
                            QuestionId = 105
                        },
                        new
                        {
                            OptionId = 1021,
                            IsCorrect = true,
                            OptionText = "mother",
                            OrderNumber = 1,
                            QuestionId = 201
                        },
                        new
                        {
                            OptionId = 1022,
                            IsCorrect = false,
                            OptionText = "eat",
                            OrderNumber = 2,
                            QuestionId = 201
                        },
                        new
                        {
                            OptionId = 1023,
                            IsCorrect = false,
                            OptionText = "blue",
                            OrderNumber = 3,
                            QuestionId = 201
                        },
                        new
                        {
                            OptionId = 1024,
                            IsCorrect = false,
                            OptionText = "quickly",
                            OrderNumber = 4,
                            QuestionId = 201
                        },
                        new
                        {
                            OptionId = 1025,
                            IsCorrect = false,
                            OptionText = "I like pizza.",
                            OrderNumber = 1,
                            QuestionId = 202
                        },
                        new
                        {
                            OptionId = 1026,
                            IsCorrect = true,
                            OptionText = "Do you like pizza?",
                            OrderNumber = 2,
                            QuestionId = 202
                        },
                        new
                        {
                            OptionId = 1027,
                            IsCorrect = false,
                            OptionText = "He playing football.",
                            OrderNumber = 3,
                            QuestionId = 202
                        },
                        new
                        {
                            OptionId = 1028,
                            IsCorrect = false,
                            OptionText = "She my sister.",
                            OrderNumber = 4,
                            QuestionId = 202
                        },
                        new
                        {
                            OptionId = 1029,
                            IsCorrect = false,
                            OptionText = "plays",
                            OrderNumber = 1,
                            QuestionId = 203
                        },
                        new
                        {
                            OptionId = 1030,
                            IsCorrect = true,
                            OptionText = "play",
                            OrderNumber = 2,
                            QuestionId = 203
                        },
                        new
                        {
                            OptionId = 1031,
                            IsCorrect = false,
                            OptionText = "playing",
                            OrderNumber = 3,
                            QuestionId = 203
                        },
                        new
                        {
                            OptionId = 1032,
                            IsCorrect = false,
                            OptionText = "played",
                            OrderNumber = 4,
                            QuestionId = 203
                        },
                        new
                        {
                            OptionId = 1033,
                            IsCorrect = true,
                            OptionText = "It's seven thirty.",
                            OrderNumber = 1,
                            QuestionId = 204
                        },
                        new
                        {
                            OptionId = 1034,
                            IsCorrect = false,
                            OptionText = "It's seven thirteen.",
                            OrderNumber = 2,
                            QuestionId = 204
                        },
                        new
                        {
                            OptionId = 1035,
                            IsCorrect = false,
                            OptionText = "It's six thirty.",
                            OrderNumber = 3,
                            QuestionId = 204
                        },
                        new
                        {
                            OptionId = 1036,
                            IsCorrect = false,
                            OptionText = "It's eight thirty.",
                            OrderNumber = 4,
                            QuestionId = 204
                        },
                        new
                        {
                            OptionId = 1037,
                            IsCorrect = true,
                            OptionText = "small",
                            OrderNumber = 1,
                            QuestionId = 205
                        },
                        new
                        {
                            OptionId = 1038,
                            IsCorrect = false,
                            OptionText = "long",
                            OrderNumber = 2,
                            QuestionId = 205
                        },
                        new
                        {
                            OptionId = 1039,
                            IsCorrect = false,
                            OptionText = "fast",
                            OrderNumber = 3,
                            QuestionId = 205
                        },
                        new
                        {
                            OptionId = 1040,
                            IsCorrect = false,
                            OptionText = "young",
                            OrderNumber = 4,
                            QuestionId = 205
                        },
                        new
                        {
                            OptionId = 1041,
                            IsCorrect = false,
                            OptionText = "cancel",
                            OrderNumber = 1,
                            QuestionId = 301
                        },
                        new
                        {
                            OptionId = 1042,
                            IsCorrect = false,
                            OptionText = "move",
                            OrderNumber = 2,
                            QuestionId = 301
                        },
                        new
                        {
                            OptionId = 1043,
                            IsCorrect = true,
                            OptionText = "reschedule",
                            OrderNumber = 3,
                            QuestionId = 301
                        },
                        new
                        {
                            OptionId = 1044,
                            IsCorrect = false,
                            OptionText = "forget",
                            OrderNumber = 4,
                            QuestionId = 301
                        },
                        new
                        {
                            OptionId = 1045,
                            IsCorrect = false,
                            OptionText = "Hey! Send me the file.",
                            OrderNumber = 1,
                            QuestionId = 302
                        },
                        new
                        {
                            OptionId = 1046,
                            IsCorrect = false,
                            OptionText = "Please send me the file now!!!",
                            OrderNumber = 2,
                            QuestionId = 302
                        },
                        new
                        {
                            OptionId = 1047,
                            IsCorrect = true,
                            OptionText = "Could you please send me the file?",
                            OrderNumber = 3,
                            QuestionId = 302
                        },
                        new
                        {
                            OptionId = 1048,
                            IsCorrect = false,
                            OptionText = "You send file.",
                            OrderNumber = 4,
                            QuestionId = 302
                        },
                        new
                        {
                            OptionId = 1049,
                            IsCorrect = false,
                            OptionText = "ask",
                            OrderNumber = 1,
                            QuestionId = 303
                        },
                        new
                        {
                            OptionId = 1050,
                            IsCorrect = false,
                            OptionText = "request",
                            OrderNumber = 2,
                            QuestionId = 303
                        },
                        new
                        {
                            OptionId = 1051,
                            IsCorrect = true,
                            OptionText = "inquire about",
                            OrderNumber = 3,
                            QuestionId = 303
                        },
                        new
                        {
                            OptionId = 1052,
                            IsCorrect = false,
                            OptionText = "say",
                            OrderNumber = 4,
                            QuestionId = 303
                        },
                        new
                        {
                            OptionId = 1053,
                            IsCorrect = false,
                            OptionText = "the place of the meeting",
                            OrderNumber = 1,
                            QuestionId = 304
                        },
                        new
                        {
                            OptionId = 1054,
                            IsCorrect = true,
                            OptionText = "the latest time to finish something",
                            OrderNumber = 2,
                            QuestionId = 304
                        },
                        new
                        {
                            OptionId = 1055,
                            IsCorrect = false,
                            OptionText = "the first day at work",
                            OrderNumber = 3,
                            QuestionId = 304
                        },
                        new
                        {
                            OptionId = 1056,
                            IsCorrect = false,
                            OptionText = "a coffee break",
                            OrderNumber = 4,
                            QuestionId = 304
                        },
                        new
                        {
                            OptionId = 1057,
                            IsCorrect = false,
                            OptionText = "send",
                            OrderNumber = 1,
                            QuestionId = 305
                        },
                        new
                        {
                            OptionId = 1058,
                            IsCorrect = true,
                            OptionText = "finish",
                            OrderNumber = 2,
                            QuestionId = 305
                        },
                        new
                        {
                            OptionId = 1059,
                            IsCorrect = false,
                            OptionText = "play",
                            OrderNumber = 3,
                            QuestionId = 305
                        },
                        new
                        {
                            OptionId = 1060,
                            IsCorrect = false,
                            OptionText = "eat",
                            OrderNumber = 4,
                            QuestionId = 305
                        },
                        new
                        {
                            OptionId = 1061,
                            IsCorrect = true,
                            OptionText = "blue",
                            OrderNumber = 1,
                            QuestionId = 401
                        },
                        new
                        {
                            OptionId = 1062,
                            IsCorrect = false,
                            OptionText = "black",
                            OrderNumber = 2,
                            QuestionId = 401
                        },
                        new
                        {
                            OptionId = 1063,
                            IsCorrect = false,
                            OptionText = "green",
                            OrderNumber = 3,
                            QuestionId = 401
                        },
                        new
                        {
                            OptionId = 1064,
                            IsCorrect = false,
                            OptionText = "yellow",
                            OrderNumber = 4,
                            QuestionId = 401
                        },
                        new
                        {
                            OptionId = 1065,
                            IsCorrect = false,
                            OptionText = "dog",
                            OrderNumber = 1,
                            QuestionId = 402
                        },
                        new
                        {
                            OptionId = 1066,
                            IsCorrect = false,
                            OptionText = "fish",
                            OrderNumber = 2,
                            QuestionId = 402
                        },
                        new
                        {
                            OptionId = 1067,
                            IsCorrect = true,
                            OptionText = "bird",
                            OrderNumber = 3,
                            QuestionId = 402
                        },
                        new
                        {
                            OptionId = 1068,
                            IsCorrect = false,
                            OptionText = "turtle",
                            OrderNumber = 4,
                            QuestionId = 402
                        },
                        new
                        {
                            OptionId = 1069,
                            IsCorrect = false,
                            OptionText = "5",
                            OrderNumber = 1,
                            QuestionId = 403
                        },
                        new
                        {
                            OptionId = 1070,
                            IsCorrect = false,
                            OptionText = "6",
                            OrderNumber = 2,
                            QuestionId = 403
                        },
                        new
                        {
                            OptionId = 1071,
                            IsCorrect = true,
                            OptionText = "7",
                            OrderNumber = 3,
                            QuestionId = 403
                        },
                        new
                        {
                            OptionId = 1072,
                            IsCorrect = false,
                            OptionText = "8",
                            OrderNumber = 4,
                            QuestionId = 403
                        },
                        new
                        {
                            OptionId = 1073,
                            IsCorrect = true,
                            OptionText = "like",
                            OrderNumber = 1,
                            QuestionId = 404
                        },
                        new
                        {
                            OptionId = 1074,
                            IsCorrect = false,
                            OptionText = "likes",
                            OrderNumber = 2,
                            QuestionId = 404
                        },
                        new
                        {
                            OptionId = 1075,
                            IsCorrect = false,
                            OptionText = "liking",
                            OrderNumber = 3,
                            QuestionId = 404
                        },
                        new
                        {
                            OptionId = 1076,
                            IsCorrect = false,
                            OptionText = "liked",
                            OrderNumber = 4,
                            QuestionId = 404
                        },
                        new
                        {
                            OptionId = 1077,
                            IsCorrect = false,
                            OptionText = "car",
                            OrderNumber = 1,
                            QuestionId = 405
                        },
                        new
                        {
                            OptionId = 1078,
                            IsCorrect = true,
                            OptionText = "banana",
                            OrderNumber = 2,
                            QuestionId = 405
                        },
                        new
                        {
                            OptionId = 1079,
                            IsCorrect = false,
                            OptionText = "chair",
                            OrderNumber = 3,
                            QuestionId = 405
                        },
                        new
                        {
                            OptionId = 1080,
                            IsCorrect = false,
                            OptionText = "pencil",
                            OrderNumber = 4,
                            QuestionId = 405
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.TestQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("TestId");

                    b.ToTable("TestQuestions");

                    b.HasData(
                        new
                        {
                            QuestionId = 101,
                            OrderNumber = 1,
                            Points = 1,
                            QuestionText = "Choose the correct option: She ___ to work every day.",
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 102,
                            OrderNumber = 2,
                            Points = 1,
                            QuestionText = "Which sentence is correct?",
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 103,
                            OrderNumber = 3,
                            Points = 1,
                            QuestionText = "What is the past simple of \"go\"?",
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 104,
                            OrderNumber = 4,
                            Points = 1,
                            QuestionText = "Choose the correct article: I have ___ orange.",
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 105,
                            OrderNumber = 5,
                            Points = 1,
                            QuestionText = "Choose the best response: \"How are you?\"",
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 201,
                            OrderNumber = 1,
                            Points = 1,
                            QuestionText = "Choose the correct word: This is my ___ . (mother / eat / blue / quickly)",
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 202,
                            OrderNumber = 2,
                            Points = 1,
                            QuestionText = "Which is a question?",
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 203,
                            OrderNumber = 3,
                            Points = 1,
                            QuestionText = "Choose the correct form: They ___ football after school.",
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 204,
                            OrderNumber = 4,
                            Points = 1,
                            QuestionText = "What time is it? 7:30",
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 205,
                            OrderNumber = 5,
                            Points = 1,
                            QuestionText = "Choose the opposite of \"big\".",
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 301,
                            OrderNumber = 1,
                            Points = 1,
                            QuestionText = "Choose the best word: We need to ___ the meeting to next Monday.",
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 302,
                            OrderNumber = 2,
                            Points = 1,
                            QuestionText = "Which sentence is appropriate in a formal email?",
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 303,
                            OrderNumber = 3,
                            Points = 1,
                            QuestionText = "Choose the correct phrase: \"I am writing to ___ information about your product.\"",
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 304,
                            OrderNumber = 4,
                            Points = 1,
                            QuestionText = "What does \"deadline\" mean?",
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 305,
                            OrderNumber = 5,
                            Points = 1,
                            QuestionText = "Choose the correct option: \"Could you please ___ the file by Friday?\"",
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 401,
                            OrderNumber = 1,
                            Points = 1,
                            QuestionText = "What color is the sky on a sunny day?",
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 402,
                            OrderNumber = 2,
                            Points = 1,
                            QuestionText = "Which animal can fly?",
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 403,
                            OrderNumber = 3,
                            Points = 1,
                            QuestionText = "How many days are there in a week?",
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 404,
                            OrderNumber = 4,
                            Points = 1,
                            QuestionText = "Choose the correct word: \"I ___ ice cream.\"",
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 405,
                            OrderNumber = 5,
                            Points = 1,
                            QuestionText = "Which one is a fruit?",
                            TestId = 4
                        });
                });

            modelBuilder.Entity("LearnLangs.Models.TestResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ResultId");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("LearnLangs.Models.UserAnswer", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAnswerId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("int");

                    b.HasKey("UserAnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("LearnLangs.Models.UserLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("UserLessons");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationItem", b =>
                {
                    b.HasOne("LearnLangs.Models.Dictation.DictationSet", "Set")
                        .WithMany("Items")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationSet", b =>
                {
                    b.HasOne("LearnLangs.Models.Dictation.DictationTopic", "Topic")
                        .WithMany("Sets")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardCard", b =>
                {
                    b.HasOne("LearnLangs.Models.Flashcards.FlashcardDeck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnLangs.Models.Flashcards.FlashcardSet", null)
                        .WithMany("Cards")
                        .HasForeignKey("FlashcardSetId");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardSet", b =>
                {
                    b.HasOne("LearnLangs.Models.Flashcards.FlashcardCategory", "Category")
                        .WithMany("Sets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.Exam", b =>
                {
                    b.HasOne("LearnLangs.Models.Games.GameLevel", "GameLevel")
                        .WithMany()
                        .HasForeignKey("GameLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLevel");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.ExamAttempt", b =>
                {
                    b.HasOne("LearnLangs.Models.Games.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.GameQuestion", b =>
                {
                    b.HasOne("LearnLangs.Models.Games.GameLevel", "GameLevel")
                        .WithMany("Questions")
                        .HasForeignKey("GameLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLevel");
                });

            modelBuilder.Entity("LearnLangs.Models.Lesson", b =>
                {
                    b.HasOne("LearnLangs.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LearnLangs.Models.Question", b =>
                {
                    b.HasOne("LearnLangs.Models.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LearnLangs.Models.QuestionOption", b =>
                {
                    b.HasOne("LearnLangs.Models.TestQuestion", "TestQuestion")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestQuestion");
                });

            modelBuilder.Entity("LearnLangs.Models.TestQuestion", b =>
                {
                    b.HasOne("LearnLangs.Models.PlacementTest", "PlacementTest")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementTest");
                });

            modelBuilder.Entity("LearnLangs.Models.TestResult", b =>
                {
                    b.HasOne("LearnLangs.Models.PlacementTest", "PlacementTest")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnLangs.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementTest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnLangs.Models.UserAnswer", b =>
                {
                    b.HasOne("LearnLangs.Models.TestQuestion", "TestQuestion")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnLangs.Models.TestResult", "TestResult")
                        .WithMany("UserAnswers")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnLangs.Models.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SelectedOption");

                    b.Navigation("TestQuestion");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("LearnLangs.Models.UserLesson", b =>
                {
                    b.HasOne("LearnLangs.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnLangs.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LearnLangs.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LearnLangs.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnLangs.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LearnLangs.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnLangs.Models.Course", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationSet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LearnLangs.Models.Dictation.DictationTopic", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardCategory", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardDeck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LearnLangs.Models.Flashcards.FlashcardSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.Exam", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("LearnLangs.Models.Games.GameLevel", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LearnLangs.Models.Lesson", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LearnLangs.Models.PlacementTest", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LearnLangs.Models.TestQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LearnLangs.Models.TestResult", b =>
                {
                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
